### ISSUE TITLE
Provider TODO list

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-ibm_power_vc#9]
TODO
- [x] manageiq-release  (ManageIQ/manageiq-release#203)
- [x] Enable miq-bot
- [x] third party services (https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/12)
- [x] Team permissions
- [x] run the labels / milestones generator on the new repo
- [x] new gitter channel
- [x] Add repo to triage list
